config/routes.rb
Rails.application.routes.draw do
  resources :artists do 
    resources :songs, only: [:new, :create, :index]
  end

  resources :songs, only: [:show, :edit, :update, :destroy]
  resources :playlists
  root 'playlists#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs

  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	has_many :playlist_songs, :dependent => :delete_all
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_many :playlist_songs, :dependent => :delete_all

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	

  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
before_action :set_artist, only: [:show, :edit, :update, :destroy]

	def index
		@artists = Artist.all
	end

	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.new(artist_params)
		if @artist.save
			flash.notice = "The artist #{@artist.name} was saved!"
			redirect_to artist_path(@artist)
		else
			flash.notice = "All artists must have a name and an image path."
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @artist.update(artist_params)

		redirect_to artist_path(@artist)
	else
		render :edit
	end
	end

	def destroy
		@artist.destroy

		redirect_to artists_path
	end

	private

	def set_artist
		@artist= Artist.find(params[:id])
	end

	def artist_params
		params.require(:artist).permit(:name, :image_path)  
	end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

def index
	@playlists = Playlist.all
end

def new
	@playlist = Playlist.new
end

def create
	@playlist = Playlist.new(playlist_params)	
		if @playlist.save
			redirect_to playlist_path(@playlist)
		else
			flash.notice = "Playlist name cannot be blank"
			render :new
		end
end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def edit
  	@playlist = Playlist.find(params[:id])
  end

  def update
	@playlist = Playlist.find(params[:id])
	@playlist.update(playlist_params)

	redirect_to playlist_path(@playlist)
end

def destroy
		@playlist = Playlist.find(params[:id])
		@playlist.destroy

		redirect_to playlists_path
	end

private

def playlist_params
	params.require(:playlist).permit(:name, song_ids: [])
end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

def index
@artist = Artist.find(params[:artist_id])
@songs = @artist.songs.order(:title)
end

def new
	@artist = Artist.find(params[:artist_id])
	@song = @artist.songs.new
end

def create
	@artist = Artist.find(params[:artist_id])
	@song = @artist.songs.new(song_params)
	if @song.save
		flash.notice = "The song #{@song.title} was saved!"
		redirect_to song_path(@song)
	else
		flash.notice = "Title cannot be blank"
		render :new
	end
end

def show
	@song = Song.find(params[:id])
end

def edit
	@song = Song.find(params[:id])
end

def update
	@song = Song.find(params[:id])
	@song.update(song_params)

	redirect_to song_path(@song)
end

def destroy
		@song = Song.find(params[:id])
		artist = @song.artist
		@song.destroy

		redirect_to artist_songs_path(artist)
	end

private 

def song_params
	params.require(:song).permit(:title)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
<div class="form-group">
<!-- <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>  -->

  <%= f.label :name %>
  <div class="form_field"><%= f.text_field :name %></div>

  <%= f.label :image_path %>
  <div class="form_field"><%= f.text_field :image_path %></div>

  <button type="submit" class="btn btn-success">Submit Artist</button>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist:</h1>

<%= render 'form' %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<table>
	<thead>
		<tr>
			<th class="t-head">Artist Name</th>
		</tr>
	</thead>
	<tbody>
	<ul>
		<% @artists.each do |artist| %>
		<tr>
			<td><li><%= link_to "#{artist.name}", artist_path(artist.id) %></li></td>
		</tr>
		<% end %>
		</ul>
	</tbody>
</table>
<br>

<%= link_to "New Artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>Create an Artist</h1>

<%= render 'form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<div class="col-md-4">
	<%= link_to "Songs by #{@artist.name}", artist_songs_path(@artist) %>
	<br>
	<%= image_tag @artist.image_path %>
	<br>
	<div class="btn-group btn-group-xs pull-right" role="group">
		<div class ="btn btn-success button-link"><%= link_to "New Song", new_artist_song_path(@artist) %></div>
		<div class="btn btn-info"><%= link_to "Update Artist", edit_artist_path(@artist) %></div>
		<div class="btn btn-danger"><%= link_to 'Delete', @artist, method: :delete, data: { confirm: 'Are you sure that you want to delete ' + @artist.name + '?' } %></div>
	</div>
</div>

app/views/layouts/application.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<%= stylesheet_link_tag "style_bitches" %>
<!DOCTYPE html>
<html>
<head>
	<title>MixMaster</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
 <a class="navbar-brand mixmaster" href="/">MixMaster</a>
	<ul class="navs pull-right">
	<li class="btn butt-content"><%= link_to "Playlists", playlists_path %></li>
	<li class="btn butt-content"><%= link_to "Artists", artists_path %></li>
	</ul>
</div>

	<p class="flash notice-styling"><%= flash.notice %></p>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <%= f.text_field :name %>

  <% Song.all.each do |song| -%>
    <div>
        <% @playlist.songs.pluck(:title).include?(song.title) ? on_list = true : on_list = false %>
      <%= check_box_tag :song_ids, song.id, on_list, :name => 'playlist[song_ids][]', id: "song-#{song.id}" %>
      <%= song.title %>
    </div>
  <% end %>

  <button type="submit" class="btn btn-success">Submit Playlist</button>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>
<%= render 'form' %>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>


<table>
	<thead>
		<tr>
			<th class="t-head">Playlist Name</th>
		</tr>
	</thead>
	<tbody>
	<ul>
		<% @playlists.each do |playlist| %>
		<tr>
			<td><li><%= link_to "#{playlist.name}", playlist_path(playlist.id) %></li></td>
		</tr>
		<% end %>
		</ul>
	</tbody>
</table>
<br>

<%= link_to "New Playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>
<%= render 'form' %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>
<ul>
  <% @playlist.songs.each do |song| %>
    <li><%= link_to song.title, song %><%= " - #{song.artist.name}" %></li>
  <% end %>
</ul>
<br>
<%= link_to "Edit", edit_playlist_path(@playlist) %>
<br>
<%= link_to "Delete", playlist_path(@playlist), method: :delete, data: { confirm: 'Are you sure that you want to delete ' + @playlist.name + '?' } %>

app/views/songs/_form.html.erb
<%= form_for([@artist, @song]) do |f| %>

<%= f.label :title %>
 <div class="form_field"><%= f.text_field :title %></div>
<button type="submit" class="btn btn-success">Submit Song</button>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit song title for <%= @song.artist.name %>:</h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<h1>Songs by <%= @artist.name %></h1>
<div class="songs-box">
<table class="table-striped table-hover table-condensed table">
<% @songs.each do |song| %>
	<tr><td><%=  link_to "#{song.title}", song_path(song) %>
	<div class="btn-group btn-group-xs pull-right" role="group">

	<div class="btn btn-info"><%= link_to "Edit", edit_song_path(song) %></div>
	<div class="btn btn-danger"><%= link_to "Delete", song_path(song), method: :delete, data: { confirm: 'Are you sure that you want to delete ' + song.title + '?' } %></div>
	</div>
	</td></tr>
<% end %>
</table>
</div>
<%= link_to "#{@artist.name}", artist_path(@artist) %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>Add a new song for <%= @artist.name %></p>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<%= link_to @song.artist.name, artist_path(@song.artist) %>
<br>
<%= link_to "Edit", edit_song_path(@song) %>
<br>
<%= link_to "Delete", song_path(@song), method: :delete, data: { confirm: 'Are you sure that you want to delete ' + @song.title + '?' } %>